# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       obexd

# >> macros
# << macros

Summary:    D-Bus service for Obex Client access
Version:    0.42
Release:    1
Group:      System/Daemons
License:    GPLv2+
URL:        http://www.bluez.org/
Source0:    http://www.kernel.org/pub/linux/bluetooth/obexd-%{version}.tar.gz
Source100:  obexd.yaml
Patch0:     add_obexd_service_desktop.patch
Patch1:     fix_sync_profile_crash.patch
BuildRequires:  pkgconfig(openobex)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(bluez) >= 4.0
BuildRequires:  pkgconfig(libical)

%description
obexd contains obex-client, a D-Bus service to allow sending files
using the Obex Push protocol, common on mobile phones and
other Bluetooth-equipped devices.


%package server
Summary:    a server for incoming OBEX connections
Group:      System/Daemons
Requires:   %{name} = %{version}-%{release}

%description server
obexd-server contains a server for receiving OBEX operations.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.

%prep
%setup -q -n %{name}-%{version}/%{name}

# add_obexd_service_desktop.patch
%patch0 -p1
# fix_sync_profile_crash.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
./bootstrap
# << build pre

%reconfigure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
chmod -x test/send-files
# << install post

%files
%defattr(-,root,root,-)
# >> files
%doc README test/send-files doc/client-api.txt COPYING AUTHORS
%{_libexecdir}/obex-client
%{_datadir}/dbus-1/services/obex-client.service
# << files

%files server
%defattr(-,root,root,-)
# >> files server
%{_libexecdir}/obexd
%{_datadir}/dbus-1/services/obexd.service
#%{_libdir}/obex/plugins/*.so
%{_sysconfdir}/xdg/autostart/obexd-server.desktop
# << files server

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc  test/send-files doc/client-api.txt
# << files devel
